name: law_platform
description: "تطبيق منصة القانون - تطبيق خاص بالأجهزة الذكية"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # حزمة دعم اللغة العربية واللغات الأخرى (RTL)
  flutter_localizations:
    sdk: flutter

  # حزمة الأيقونات الإضافية
  cupertino_icons: ^1.0.8

  # لحفظ الرمز السري وحالة تسجيل دخول البوابة الآمنة محلياً
  shared_preferences: ^2.2.2

  # لاختيار الصور من المعرض والكاميرا
  image_picker: ^1.0.7

  # 🌐 حزمة إرسال الطلبات لرفع الصور لسيرفر الرفع المجاني
  http: ^1.2.0

  # 🔗 حزمة فتح الروابط الخارجية وملفات الـ PDF
  url_launcher: ^6.3.0

  # --- حزم الفايربيس للخدمات السحابية ---
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1

  # --- حزم رفع وعرض ملفات الـ PDF ---
  supabase_flutter: ^2.5.0
  file_picker: ^8.0.3
  syncfusion_flutter_pdfviewer: ^25.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # حزمة تغيير اسم التطبيق المعتمدة
  rename: ^3.0.2

flutter:
  uses-material-design: true
